#!/usr/bin/env python3
"""
DEFs for header variable tags
"""
HEADERDEFS =    [\
                'START_OF_LOG',
                'CALLSIGN',
                'OPERATORS',
                'CONTEST',
                'LOCATION',
                'CATEGORY_BAND',
                'CATEGORY_MODE',
                'CATEGORY_OPERATOR',
				'CATEGORY_POWER',
                'CATEGORY_STATION',
                'CATEGORY_TRANSMITTER',
                'CATEGORY_OVERLAY',
                'CATEGORY_ASSISTED',
                'CATEGORY_TIME',
                'CERTIFICATE',
                'CLUB',
                'CLAIMED_SCORE',
                'CREATED_BY',
                'EMAIL',
                'NAME',
                'ADDRESS',
                'ADDRESS_CITY',
                'ADDRESS_STATE_PROVINCE',
                'ADDRESS_POSTALCODE',
                'ADDRESS_COUNTRY',
                'OFFTIME',
                'GRID_LOCATOR',
                'SOAPBOX',
                'END_OF_LOG']
                
DBHEADERDEFS =  [\
                'START',	
                'CALLSIGN',
                'OPERATORS',
                'CONTEST',
                'LOCATION',
                'CATBAND',
                'CATMODE',
                'CATOPERATOR',
                'CATPOWER',
                'CATSTATION',
                'CATXMITTER',
                'CATOVERLAY',
                'CATASSISTED',
                'CATEGORY_TIME', # Not used in db!
                'CERTIFICATE',
                'CLUB',
                'CLAIMEDSCORE',
                'CREATEDBY',
                'EMAIL',
                'NAME',
                'ADDRESS',
                'CITY',
                'STATEPROV',
                'ZIPCODE',
                'COUNTRY',
                'OFFTIME',
                'GRID_LOCATOR', #Not used in db
                'SOAPBOX',
                'ENDOFLOG',
                'IOTAISLANDNAME',
                'ID',
                'MOQPCAT',
                'STATUS',
                'CABBONUS',
                'TIMESTAMP']
                
QSODEFS =   [\
            'freq',
            'mode',
            'qtime',
            'mycall',
            'myrst',
            'myqth',
            'urcall',
            'urrst',
            'urqth',
            'valid',
            'dupe',
            'qdata']
            
DBQSODEFS=  [\
            'FREQ',
            'MODE',
            'DATETIME',
            'MYCALL',
            'MYREPORT',
            'MYQTH',
            'URCALL',
            'URREPORT',
            'URQTH',
            'VALID',
            'QSL',
            'DUPE',
            'NOTE',
            'ID',
            'LOGID',
            'QSL',
            'NOLOG',
            'NOQSOS']
			